
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: zanzibar-dag
      POSTGRES_PASSWORD: zanzibar-dag
      POSTGRES_DB: zanzibar-dag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zanzibar-dag:
   image: zanzibar-dag:latest
   ports:
   - "8080:8080"

volumes:
  postgres_data: